# This file is part of Astarte.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Docker images
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to checkout and release'
        required: true
        type: string
env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/astarte-message-hub
jobs:
  push_release_to_registry:
    name: Push Docker images to registry
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
    steps:
      - name: Check out the repo at specified tag
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.tag }}
      - name: Log in to registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Set docker metadata required tag information
        id: tag-types
        run: |
          echo "metadata<<EOF" >> $GITHUB_OUTPUT
          if [[ -z "${{ inputs.tag }}" ]]; then
            echo "type=semver,pattern={{version}}" >> $GITHUB_OUTPUT
          else
            echo "type=semver,pattern={{version}},value=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@a60f0f62b5c12316066c8db464bfb2faafd7907b
        with:
          images: ${{ env.IMAGE }}
          tags: |
            ${{ steps.tag-types.outputs.metadata }}
      - name: Build and push tagged Docker image
        id: push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          file: scripts/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
