# This file is part of Astarte.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Publish snapshot Docker images
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'The branch, tag or SHA to checkout'
        required: true
        type: string
env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/astarte-message-hub
jobs:
  push_snapshot_to_registry:
    name: Push Docker images to registry
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo at the specified ref
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit-sha }}
      - name: Log in to registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Compute tag name for snapshot images
        id: compute-tag
        run: |
          # ${{ github.ref }} references the ref of the branch or tag that triggered the worflow run
          # we need to handle dispatched invocations so we use this git command
          REF=$(git symbolic-ref HEAD)
          export TAG="$(echo $REF | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-\(.*\)/\1-snapshot/g' )"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@a60f0f62b5c12316066c8db464bfb2faafd7907b
        with:
          images: ${{ env.IMAGE }}
          tags: |
            # TODO we probably want something smarter, but the 'pattern' type runs only on tags at the moment
            type=raw,value=${{ steps.compute-tag.outputs.TAG }}
      - name: Build and push tagged Docker image
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          file: scripts/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
